"""memoria

Revision ID: fb046b21393b
Revisione precedente: 5793e2e92add
Creata: 2026-09-21 21:26:13.436373+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'fb046b21393b'
down_revision: Union[str, None] = '5793e2e92add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_accesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_accesses_created_at'), 'memory_accesses', ['created_at'], unique=False)
    op.create_index('ix_memory_accesses_soggetto', 'memory_accesses', ['subject_id', 'created_at'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('personality_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('times_referenced', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_referenced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('identita', 'preferenza', 'fatto', 'impegno', 'sessione')", name='ck_memories_kind'),
    sa.CheckConstraint('confidence >= 0 and confidence <= 1', name='ck_memories_confidence'),
    sa.CheckConstraint('importance >= 0 and importance <= 1', name='ck_memories_importance'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by'], ['memories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_hnsw', 'memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memories_scadenza', 'memories', ['expires_at'], unique=False)
    op.create_index('ix_memories_utente_personalita', 'memories', ['user_id', 'personality_id'], unique=False)
    op.create_index('ix_memories_utente_valide', 'memories', ['user_id', 'valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memories_utente_valide', table_name='memories')
    op.drop_index('ix_memories_utente_personalita', table_name='memories')
    op.drop_index('ix_memories_scadenza', table_name='memories')
    op.drop_index('ix_memories_hnsw', table_name='memories', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memories')
    op.drop_index('ix_memory_accesses_soggetto', table_name='memory_accesses')
    op.drop_index(op.f('ix_memory_accesses_created_at'), table_name='memory_accesses')
    op.drop_table('memory_accesses')
    # ### end Alembic commands ###
