"""etichette della digestione

Revision ID: 4c2b0d30556f
Revisione precedente: fb046b21393b
Creata: 2026-09-21 22:01:42.011712+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '4c2b0d30556f'
down_revision: Union[str, None] = 'fb046b21393b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chunks', sa.Column('label_main', sa.String(length=20), nullable=True))
    op.add_column('chunks', sa.Column('provenance', sa.String(length=20), nullable=True))
    op.add_column('chunks', sa.Column('quality', sa.Float(), nullable=True))
    # `server_default` e non solo `nullable=False`: la tabella ha gia' righe,
    # e il vincolo verrebbe creato su valori nulli. Il default resta anche
    # dopo, cosi' un passaggio inserito senza passare dall'ORM nasce comunque
    # «non scartato» invece che in uno stato indefinito.
    op.add_column(
        'chunks',
        sa.Column(
            'discarded', sa.Boolean(), nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('chunks', sa.Column('discard_reason', sa.Text(), nullable=True))
    op.create_index('ix_chunks_kb_vivi', 'chunks', ['kb_id', 'discarded', 'label_main'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_kb_vivi', table_name='chunks')
    op.drop_column('chunks', 'discard_reason')
    op.drop_column('chunks', 'discarded')
    op.drop_column('chunks', 'quality')
    op.drop_column('chunks', 'provenance')
    op.drop_column('chunks', 'label_main')
    op.drop_column('chunks', 'labels')
    # ### end Alembic commands ###
