"""pagamenti predisposti

Revision ID: 93be1f9481b8
Revisione precedente: d957fd1a8d29
Creata: 2026-09-22 12:39:38.832331+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '93be1f9481b8'
down_revision: Union[str, None] = 'd957fd1a8d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_checkouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('annuale', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('subscription_external_id', sa.String(length=120), nullable=True),
    sa.Column('importo', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('aperto', 'pagato', 'annullato', 'scaduto')", name='ck_payment_checkouts_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_checkouts_utente', 'payment_checkouts', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_checkouts_utente', table_name='payment_checkouts')
    op.drop_table('payment_checkouts')
    op.drop_table('payment_events')
    # ### end Alembic commands ###
