"""configurazione testuale della base

Revision ID: a8b35b7b278f
Revisione precedente: e47802498748
Creata: 2026-09-21 18:39:26.081791+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy


revision: str = 'a8b35b7b278f'
down_revision: Union[str, None] = 'e47802498748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # In tre passi e non in uno: la colonna è `NOT NULL` e la tabella può già
    # contenere righe, che altrimenti violerebbero il vincolo nell'istante in
    # cui viene creato.
    op.add_column(
        'knowledge_bases',
        sa.Column('text_config', sa.String(length=30), nullable=True),
    )

    # Le basi esistenti sono state indicizzate prima che questa colonna ci
    # fosse: il loro `tsv` è già scritto in una configurazione precisa, e
    # assegnarne un'altra le renderebbe irraggiungibili dalla ricerca
    # lessicale. Si deduce dalla lingua registrata sui documenti, e si ricade
    # su `simple` dove non è nota.
    op.execute("""
        UPDATE knowledge_bases kb
        SET text_config = COALESCE((
            SELECT CASE d.meta ->> 'lingua'
                WHEN 'it' THEN 'italian'
                WHEN 'en' THEN 'english'
                WHEN 'fr' THEN 'french'
                WHEN 'de' THEN 'german'
                WHEN 'es' THEN 'spanish'
                WHEN 'pt' THEN 'portuguese'
                WHEN 'nl' THEN 'dutch'
                WHEN 'ru' THEN 'russian'
                ELSE 'simple'
            END
            FROM documents d
            WHERE d.kb_id = kb.id
            ORDER BY d.created_at
            LIMIT 1
        ), 'simple')
    """)

    op.alter_column('knowledge_bases', 'text_config', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'text_config')
    # ### end Alembic commands ###
