"""realizzazioni

Revision ID: 5793e2e92add
Revisione precedente: 20f3de788735
Creata: 2026-09-21 19:37:28.563017+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '5793e2e92add'
down_revision: Union[str, None] = '20f3de788735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('personality_version_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('artifact_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind in ('lora', 'finetune', 'gguf', 'merge')", name='ck_builds_kind'),
    sa.CheckConstraint("status in ('in_coda', 'in_corso', 'riuscita', 'fallita', 'annullata')", name='ck_builds_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personality_version_id'], ['personality_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_builds_owner_creazione', 'builds', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_builds_personalita', 'builds', ['personality_id', 'created_at'], unique=False)
    op.create_index('ix_builds_stato', 'builds', ['status'], unique=False)
    op.create_table('build_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_events_build', 'build_events', ['build_id', 'created_at'], unique=False)
    op.create_table('runtime_bindings',
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('serving', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode in ('rag', 'lora', 'finetune')", name='ck_runtime_mode'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('personality_id'),
    sa.UniqueConstraint('personality_id', name='uq_runtime_una_per_personalita')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_bindings')
    op.drop_index('ix_build_events_build', table_name='build_events')
    op.drop_table('build_events')
    op.drop_index('ix_builds_stato', table_name='builds')
    op.drop_index('ix_builds_personalita', table_name='builds')
    op.drop_index('ix_builds_owner_creazione', table_name='builds')
    op.drop_table('builds')
    # ### end Alembic commands ###
