"""indice sul proprietario delle personalita

Revision ID: 2467bfd81565
Revisione precedente: a8b35b7b278f
Creata: 2026-09-21 18:42:34.023739+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy


revision: str = '2467bfd81565'
down_revision: Union[str, None] = 'a8b35b7b278f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_personalities_owner_status', 'personalities', ['owner_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_personalities_owner_status', table_name='personalities')
    # ### end Alembic commands ###
