"""laboratorio: voti ed esperimenti

Revision ID: 8415f60b5014
Revisione precedente: 8e41f6c2a7d3
Creata: 2026-09-22 18:00:00+00:00

Il voto sulle risposte e gli esperimenti fra versioni: la metrica e il
confronto che la usa.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '8415f60b5014'
down_revision: Union[str, None] = '8e41f6c2a7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('winner_version_id', sa.Uuid(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('attivo', 'concluso')", name='ck_experiments_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_version_id'], ['personality_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_experiments_attivo_per_personalita', 'experiments', ['personality_id'], unique=True, postgresql_where=sa.text("status = 'attivo'"))
    op.create_table('answer_feedback',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('vote', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('vote in (-1, 1)', name='ck_answer_feedback_vote'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_answer_feedback_creazione', 'answer_feedback', ['created_at'], unique=False)
    op.create_index('ix_answer_feedback_utente', 'answer_feedback', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('experiment_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_conversations_experiment_id'), 'conversations', ['experiment_id'], unique=False)
    op.create_foreign_key('fk_conversations_experiment_id', 'conversations', 'experiments', ['experiment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_experiment_id', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_experiment_id'), table_name='conversations')
    op.drop_column('conversations', 'experiment_id')
    op.drop_index('ix_answer_feedback_utente', table_name='answer_feedback')
    op.drop_index('ix_answer_feedback_creazione', table_name='answer_feedback')
    op.drop_table('answer_feedback')
    op.drop_index('uq_experiments_attivo_per_personalita', table_name='experiments', postgresql_where=sa.text("status = 'attivo'"))
    op.drop_table('experiments')
    # ### end Alembic commands ###
