"""testo originale dei passaggi

Revision ID: 5ff29b163aed
Revisione precedente: 4c2b0d30556f
Creata: 2026-09-21 22:25:43.329281+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy


revision: str = '5ff29b163aed'
down_revision: Union[str, None] = '4c2b0d30556f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('text_original', sa.Text(), nullable=True))
    op.alter_column('chunks', 'discarded',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'discarded',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('chunks', 'text_original')
    # ### end Alembic commands ###
