"""digestione come job

Revision ID: a98d1bcae6b5
Revisione precedente: d426afca5152
Creata: 2026-09-21 23:23:55.620343+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy


revision: str = 'a98d1bcae6b5'
down_revision: Union[str, None] = 'd426afca5152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('builds', 'personality_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('builds', 'personality_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
