"""tipi e categorie commerciali

Revision ID: 20f3de788735
Revisione precedente: 2467bfd81565
Creata: 2026-09-21 19:12:19.200666+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# L'autogenerazione scrive `pgvector.sqlalchemy.Vector(...)` nelle colonne di
# embedding ma non ne emette l'import: senza questa riga la migrazione
# fallisce con `NameError` al momento di applicarla, non di generarla.
import pgvector.sqlalchemy


revision: str = '20f3de788735'
down_revision: Union[str, None] = '2467bfd81565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank', name='uq_commercial_categories_rank'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('personality_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('personality_type_map',
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['personality_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('personality_id', 'type_id')
    )
    op.add_column('personalities', sa.Column('commercial_category_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'personalities', 'commercial_categories', ['commercial_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'personalities', type_='foreignkey')
    op.drop_column('personalities', 'commercial_category_id')
    op.drop_table('personality_type_map')
    op.drop_table('personality_types')
    op.drop_table('commercial_categories')
    # ### end Alembic commands ###
