"""conoscenza e personalita

Revision ID: e47802498748
Revisione precedente: 4480a30c7f4e
Creata: 2026-09-21 18:24:21.694694+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'e47802498748'
down_revision: Union[str, None] = '4480a30c7f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('embed_model', sa.String(length=120), nullable=False),
    sa.Column('embed_dim', sa.Integer(), nullable=False),
    sa.Column('chunk_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind in ('corpus', 'reference', 'news')", name='ck_kb_kind'),
    sa.CheckConstraint("visibility in ('private', 'shared', 'public')", name='ck_kb_visibility'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_knowledge_bases_owner_slug', 'knowledge_bases', ['owner_id', 'slug'], unique=False)
    op.create_table('personalities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status in ('draft', 'published', 'archived')", name='ck_personalities_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kb_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'sha256', name='uq_documents_kb_sha')
    )
    op.create_index('ix_documents_kb', 'documents', ['kb_id'], unique=False)
    op.create_table('personality_kb',
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('kb_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_chunks', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role in ('voice', 'knowledge')", name='ck_personality_kb_role'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('personality_id', 'kb_id')
    )
    op.create_table('personality_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('personality_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('behavior_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rag_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memory_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guard_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personality_id', 'version', name='uq_version_per_personality')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('kb_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunks_doc_ordinal')
    )
    op.create_index('ix_chunks_kb', 'chunks', ['kb_id'], unique=False)
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('chunk_vectors',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('kb_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('embedded_with', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunk_vectors_hnsw', 'chunk_vectors', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunk_vectors_kb', 'chunk_vectors', ['kb_id'], unique=False)
    op.create_table('answer_traces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('personality_version_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grounding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guard_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personality_version_id'], ['personality_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_answer_traces_created_at'), 'answer_traces', ['created_at'], unique=False)
    op.add_column('conversations', sa.Column('personality_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('personality_version_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'personalities', ['personality_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversations', 'personality_versions', ['personality_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'personality_version_id')
    op.drop_column('conversations', 'personality_id')
    op.drop_index(op.f('ix_answer_traces_created_at'), table_name='answer_traces')
    op.drop_table('answer_traces')
    op.drop_index('ix_chunk_vectors_kb', table_name='chunk_vectors')
    op.drop_index('ix_chunk_vectors_hnsw', table_name='chunk_vectors', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunk_vectors')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_kb', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('personality_versions')
    op.drop_table('personality_kb')
    op.drop_index('ix_documents_kb', table_name='documents')
    op.drop_table('documents')
    op.drop_table('personalities')
    op.drop_index('ix_knowledge_bases_owner_slug', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
